### ISSUE TITLE
Please clarify what JSON API is

### ISSUE THREAD

**Issue by valgog** [zalando/scala-jsonapi#11]
Could you please provide some links to the specification of `JSON API`? As far as I understand it is not `JSON-schema` or is it?

**Comment by asgoncalves** [comment]
http://jsonapi.org/

From the link above: "JSON API is a specification for how a client should request resources to be fetched or modified, and how a server should respond to those requests."

**Comment by zmeda** [comment]
This link is also provided in the readme.
