### ISSUE TITLE
ResourceObject needs to have "id" property as an Option[String]

### ISSUE THREAD

**Issue by texvex** [zalando/scala-jsonapi#20]
Hi,

I'm trying to implement your nice library. 
I have a problem when I want to create a resource.

in the specification id is not mandatory : 
http://jsonapi.org/format/#document-resource-objects

Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server.

Thanks,

Jeremie

**Comment by zmeda** [comment]
Hi Jeremie,

First of all thanks for showing the interest to the library.
We are aware of that and we will fix it in the next release. It was meant to be a part of issue #10 . But since there is a need for that we will fix it right away.

Best,
Boris

**Comment by texvex** [comment]
Hi Boris,
thanks for your quick reply, 
I'm using your library with play 2.3 (thanks a lot for your last release 0.3.0 !!)

At this time, everything works fine.

best regards, 

Jeremie

**Comment by zmeda** [comment]
We haven't fully tested integration with Play-JSON. Basically just with tests.
So any feedback would be more then appreciated. We are glad that it works fine now! :+1: 

PR will be soon merged and issue should be solved.

Best,
Boris

**Comment by texvex** [comment]
Awsome ! 
thanks,

For the moment, we implement  only simple resourceObject (no ResourceObjects) with some relations, links and meta.
Play Reader and Writer work fine ! 
we still have to implement errors. but i m sure it will be OK !

best regards,
Jeremie
