### ISSUE TITLE
Any plan to support Play 2.5 and json with relationship

### ISSUE THREAD

**Issue by ysihaoy** [zalando/scala-jsonapi#32]
Any ETA for those support? Thanks.

**Comment by zmeda** [comment]
Hey @ysihaoy !

I was planning to do it next week. So expect it to be done in CW13. I'll create milestone and issue for that.

Thanks for interest and check gitter for activity. ;)

**Comment by ysihaoy** [comment]
Cool, nice. Really excited to see this so we don't need to write ourselves.

Good framework!
