### ISSUE TITLE
Unable to create user-defined document links

### ISSUE THREAD

**Issue by wlk** [zalando/scala-jsonapi#35]
Currently it's not possible to create user-defined document links. There is a predefined list to choose from:
```
Self
Related
Fist
Last
Next
Prev
About
```

According to specs: http://jsonapi.org/format/#document-links There is no mention of a fixed list of allowed document links (You might have implemented pagination links: http://jsonapi.org/format/#fetching-pagination )

**Comment by wlk** [comment]
small correction:
if fact what you have so far is correct, top level links must belong to that list of allowed types (for RootObject), but ResourceObject links can be of any type

**Comment by Unisay** [comment]
Sorry for the delay, the maintainer @zmeda will answer asap (I think he is on vacation right now)

**Comment by wlk** [comment]
No problem, I'm happy to provide a fix, but would just require confirmation that my thinking in last comment is correct

**Comment by zmeda** [comment]
As agreed in PR there is no specific definition whether we can have custom links or no. Closing then.

**Comment by toddkazakov** [comment]
@zmeda I'd like to reopen this. The specification itself doesn't **explicitly** mention additional links, but the [json schema](http://jsonapi.org/schema) does. 

Successful response uses `links`, which extend from both `#/definitions/pagination` and `#/definitions/links`. `#/definitions/links` **explicitly** allows for additional keys (`additionalProperties: true`).
