### ISSUE TITLE
Inconsistency handling error links

### ISSUE THREAD

**Issue by wlk** [zalando/scala-jsonapi#41]
`Error` objects are allowed to have `links` only with `about` member: http://jsonapi.org/format/#error-objects
Right now scala-jsonapi allows to create links with any type of allowed link.

At the same time, RootObject can't have `about` member as part of the `links`

> The top-level links object MAY contain the following members:
> 
> self: the link that generated the current response document.
> related: a related resource link when the primary data represents a resource relationship.
> pagination links for the primary data.

**Comment by asgoncalves** [comment]
we are still not doing these validations (see issue #6)
but we are planning on solving these issues in the future.

**Comment by LappleApple** [comment]
@wlk @asgoncalves Do we need to leave this issue open, or is it resolved?
