### ISSUE TITLE
The library should support reads also

### ISSUE THREAD

**Issue by zmeda** [zalando/scala-jsonapi#8]
The library now supports "only" writers but wit should be read-ready.

**Comment by mplatt** [comment]
Thanks for this cool library. I came across the same requirement (having to de-serialize JSONAPI). As I am using Play 2.4 it is very easy to achieve this with formats. You probably do not want any dependency to Play, but if you were using it, this was how it could be achieved: https://gist.github.com/mplatt/b645ff345d792f9cb9c5

**Comment by zmeda** [comment]
Nice to hear that you like this library. There is [another issue](https://github.com/zalando/scala-jsonapi/issues/9) which actually will add Play-JSON support. We liked your idea. We have to come up with implementation for older Play versions.
Plans are to finish this week the read support and also the Play-JSON support.

**Comment by mplatt** [comment]
Just out of curiosity; what would your Play version requirements be?

**Comment by zmeda** [comment]
We were thinking more to add 2.3 support since a lot of people are using 2.3. What do you think?

**Comment by mplatt** [comment]
2.3 is an easy fix if you're going with org.cvogt.play.json.Jsonx. Would you be interested in making this library more opinionated towards Play (i.e. make Play a requisite)?

**Comment by zmeda** [comment]
No... We want to provide library that will be specific JSON implementation independent. So for now we have two "layers". Domain model part which in JSON independent. And the specific JSON implementation part. So far in the latter we support only Spray-JSON which we are using in our internal implementation. But as said we will provide also support for Play_JSON by the end of this week (at least that is a plan).
Again we want to be Play, Spray, json4s,... independent. This is "just" an implementation detail which you can choose when adding dependencies.

**Comment by zmeda** [comment]
Read support for both Play-JSON and Spray-JSON is implemented in version 0.3.0.
